# Generated by Django 5.2.11 on 2026-02-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descriptin',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
    ]
